-- AlterTable
ALTER TABLE "User" ADD COLUMN "pveWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pveLosses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pveDraws" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pveTotalFights" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pvpWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pvpLosses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pvpDraws" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "pvpTotalFights" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "totalTaps" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "progression" JSONB;
ALTER TABLE "User" ADD COLUMN "deck" JSONB;
ALTER TABLE "User" ADD COLUMN "settings" JSONB;
