require('dotenv').config();

module.exports = {
  PORT: parseInt(process.env.PORT || '3000'),
  WS_PORT: parseInt(process.env.WS_PORT || '444'),
  JWT_SECRET: process.env.JWT_SECRET || 'default-secret',
  FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:5173',
  UPLOAD_DIR: process.env.UPLOAD_DIR || './uploads',
  DECIMALS: 6,
  COST_PER_CLICK: 2,
  COST_CREATE_CLUB: 10000,
  PUNCH_MAX_PER_INTERVAL: 10000,
  PUNCH_MAX_PER_BATCH: 10000,
  PUNCH_INTERVAL_MS: 3600000, // 1 hour

  // PvP Combat
  MAX_HP: 100,
  MAX_ROUNDS: 10,
  EXTRA_ROUNDS: 2,
  EXTRA_ROUND_DAMAGE_MULTIPLIER: 2,
  TOTAL_ROUNDS: 12,
  MAX_DECK_SIZE: 8,
  MIN_DECK_SIZE: 4,
  COUNTDOWN_MS: 3000,
  ROUND_ANIMATION_MS: 1500,
  BASE_DAMAGE: 15,
  POSITION_BONUS: 5,
  DICE_COOLDOWN_ROUNDS: 3,
  DICE_PAUSE_TIMEOUT_MS: 10000,
  EMERGENCY_HP_THRESHOLD: 30,
  COACH_MIN_ROUND: 6,
  COACH_BOOST_ROUNDS: 4,
  COACH_PAUSE_TIMEOUT_MS: 10000,
};
