-- AlterTable: Add rating to User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rating" INTEGER NOT NULL DEFAULT 1000;

-- AlterTable: Add PvP fields to Fight
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'pve';
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "matchId" TEXT;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "player1Id" TEXT;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "player2Id" TEXT;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "player1Hp" INTEGER;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "player2Hp" INTEGER;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "winner" TEXT;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "reason" TEXT NOT NULL DEFAULT 'normal';
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "rounds" INTEGER;
ALTER TABLE "Fight" ADD COLUMN IF NOT EXISTS "roundLog" JSONB;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Fight_player1Id_idx" ON "Fight"("player1Id");
CREATE INDEX IF NOT EXISTS "Fight_player2Id_idx" ON "Fight"("player2Id");
CREATE INDEX IF NOT EXISTS "Fight_matchId_idx" ON "Fight"("matchId");
